import sqlite3
import json
import uuid
import pandas as pd
from datetime import datetime
from typing import Dict, List, Any, Optional

import sys
from pathlib import Path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import config


class CaseManager:
    """
    Enterprise Case Management & Alert Triage System backed by SQLite.
    Maintains full audit trails, investigator assignment, and lifecycle states.
    """

    VALID_STATUSES = [
        "NEW",
        "ASSIGNED",
        "UNDER_INVESTIGATION",
        "CONFIRMED_FRAUD",
        "FALSE_POSITIVE",
        "CLEARED",
    ]

    def __init__(self, db_path: Path = config.DATABASE_PATH):
        self.db_path = str(db_path)
        self._init_db()

    def _get_connection(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        return conn

    def _init_db(self) -> None:
        """Initializes database schema if not present."""
        with self._get_connection() as conn:
            cursor = conn.cursor()
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cases (
                    case_id TEXT PRIMARY KEY,
                    transaction_id TEXT UNIQUE,
                    user_id TEXT,
                    card_id TEXT,
                    device_id TEXT,
                    ip_address TEXT,
                    amount REAL,
                    risk_score REAL,
                    risk_tier TEXT,
                    fraud_typology TEXT,
                    status TEXT,
                    assigned_investigator TEXT,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP,
                    rules_triggered TEXT,
                    explanation_narrative TEXT,
                    notes TEXT
                );
            """)

            cursor.execute("""
                CREATE TABLE IF NOT EXISTS audit_log (
                    log_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    case_id TEXT,
                    timestamp TIMESTAMP,
                    actor TEXT,
                    action TEXT,
                    notes TEXT,
                    FOREIGN KEY (case_id) REFERENCES cases(case_id)
                );
            """)
            conn.commit()

    def create_case(
        self,
        transaction_id: str,
        user_id: str,
        card_id: str,
        device_id: str,
        ip_address: str,
        amount: float,
        risk_score: float,
        risk_tier: str,
        fraud_typology: str = "Suspicious Velocity",
        rules_triggered: List[Dict[str, Any]] = None,
        explanation_narrative: str = "",
        assigned_investigator: Optional[str] = "Unassigned",
        initial_notes: str = "Automated high-risk alert generated by Detection Platform.",
    ) -> str:
        """Creates a new fraud investigation case from an alert."""
        case_id = f"CASE-{datetime.utcnow().strftime('%Y%m')}-{uuid.uuid4().hex[:6].upper()}"
        now = datetime.utcnow().isoformat()

        rules_json = json.dumps(rules_triggered or [])

        with self._get_connection() as conn:
            cursor = conn.cursor()
            # Check if case for this transaction already exists
            cursor.execute("SELECT case_id FROM cases WHERE transaction_id = ?", (transaction_id,))
            existing = cursor.fetchone()
            if existing:
                return existing["case_id"]

            cursor.execute("""
                INSERT INTO cases (
                    case_id, transaction_id, user_id, card_id, device_id, ip_address,
                    amount, risk_score, risk_tier, fraud_typology, status,
                    assigned_investigator, created_at, updated_at, rules_triggered,
                    explanation_narrative, notes
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                case_id, transaction_id, user_id, card_id, device_id, ip_address,
                amount, risk_score, risk_tier, fraud_typology, "NEW",
                assigned_investigator, now, now, rules_json,
                explanation_narrative, initial_notes,
            ))

            cursor.execute("""
                INSERT INTO audit_log (case_id, timestamp, actor, action, notes)
                VALUES (?, ?, ?, ?, ?)
            """, (case_id, now, "SYSTEM", "ALERT_TRIGGERED", initial_notes))

            conn.commit()

        return case_id

    def list_cases(
        self,
        status: Optional[str] = None,
        risk_tier: Optional[str] = None,
        limit: int = 100,
    ) -> List[Dict[str, Any]]:
        """Retrieves cases filtered by status and severity tier."""
        query = "SELECT * FROM cases WHERE 1=1"
        params = []

        if status and status != "ALL":
            query += " AND status = ?"
            params.append(status)

        if risk_tier and risk_tier != "ALL":
            query += " AND risk_tier = ?"
            params.append(risk_tier)

        query += " ORDER BY risk_score DESC, updated_at DESC LIMIT ?"
        params.append(limit)

        with self._get_connection() as conn:
            cursor = conn.cursor()
            cursor.execute(query, params)
            rows = cursor.fetchall()

        cases = []
        for r in rows:
            case_dict = dict(r)
            try:
                case_dict["rules_triggered"] = json.loads(case_dict["rules_triggered"] or "[]")
            except Exception:
                case_dict["rules_triggered"] = []
            cases.append(case_dict)
        return cases

    def get_case(self, case_id: str) -> Optional[Dict[str, Any]]:
        """Fetches full case details including audit history."""
        with self._get_connection() as conn:
            cursor = conn.cursor()
            cursor.execute("SELECT * FROM cases WHERE case_id = ?", (case_id,))
            case_row = cursor.fetchone()
            if not case_row:
                return None

            cursor.execute("SELECT * FROM audit_log WHERE case_id = ? ORDER BY timestamp ASC", (case_id,))
            audit_rows = cursor.fetchall()

        case_dict = dict(case_row)
        try:
            case_dict["rules_triggered"] = json.loads(case_dict["rules_triggered"] or "[]")
        except Exception:
            case_dict["rules_triggered"] = []

        case_dict["audit_history"] = [dict(a) for a in audit_rows]
        return case_dict

    def update_case_status(
        self,
        case_id: str,
        new_status: str,
        actor: str = "Investigator",
        notes: str = "",
        assigned_investigator: Optional[str] = None,
    ) -> bool:
        """Updates case workflow status, assigns investigator, and logs audit record."""
        if new_status not in self.VALID_STATUSES:
            raise ValueError(f"Invalid status: {new_status}. Must be one of {self.VALID_STATUSES}")

        now = datetime.utcnow().isoformat()

        with self._get_connection() as conn:
            cursor = conn.cursor()
            if assigned_investigator:
                cursor.execute("""
                    UPDATE cases
                    SET status = ?, assigned_investigator = ?, updated_at = ?, notes = notes || '\n' || ?
                    WHERE case_id = ?
                """, (new_status, assigned_investigator, now, f"[{now}] {actor}: {notes}", case_id))
            else:
                cursor.execute("""
                    UPDATE cases
                    SET status = ?, updated_at = ?, notes = notes || '\n' || ?
                    WHERE case_id = ?
                """, (new_status, now, f"[{now}] {actor}: {notes}", case_id))

            cursor.execute("""
                INSERT INTO audit_log (case_id, timestamp, actor, action, notes)
                VALUES (?, ?, ?, ?, ?)
            """, (case_id, now, actor, f"STATUS_CHANGE_TO_{new_status}", notes))

            conn.commit()
            return cursor.rowcount > 0

    def get_summary_metrics(self) -> Dict[str, Any]:
        """Calculates key operational SOC/FOC metrics."""
        with self._get_connection() as conn:
            cursor = conn.cursor()

            cursor.execute("SELECT COUNT(*), COALESCE(SUM(amount), 0) FROM cases")
            total_cases, total_flagged_dollars = cursor.fetchone()

            cursor.execute("SELECT COUNT(*) FROM cases WHERE status IN ('NEW', 'ASSIGNED', 'UNDER_INVESTIGATION')")
            open_cases = cursor.fetchone()[0]

            cursor.execute("SELECT COUNT(*), COALESCE(SUM(amount), 0) FROM cases WHERE status = 'CONFIRMED_FRAUD'")
            confirmed_fraud_count, confirmed_fraud_dollars = cursor.fetchone()

            cursor.execute("SELECT COUNT(*) FROM cases WHERE status = 'FALSE_POSITIVE'")
            fp_count = cursor.fetchone()[0]

            cursor.execute("SELECT COUNT(*) FROM cases WHERE risk_tier = 'CRITICAL'")
            critical_alerts = cursor.fetchone()[0]

        resolved_count = (total_cases - open_cases)
        fp_rate = (fp_count / resolved_count * 100) if resolved_count > 0 else 0.0

        return {
            "total_cases": total_cases,
            "open_cases": open_cases,
            "resolved_cases": resolved_count,
            "confirmed_fraud_count": confirmed_fraud_count,
            "confirmed_fraud_dollars": round(confirmed_fraud_dollars, 2),
            "total_flagged_dollars": round(total_flagged_dollars, 2),
            "false_positive_rate_pct": round(fp_rate, 2),
            "critical_alerts_count": critical_alerts,
        }

    def seed_from_scored_dataset(self, scored_df: pd.DataFrame, limit: int = 150) -> int:
        """Seeds case database with realistic high-risk cases from scored transactions."""
        high_risk = scored_df[scored_df["composite_risk_score"] >= config.THRESHOLD_HIGH].head(limit)
        seeded = 0

        for _, row in high_risk.iterrows():
            typology = row.get("fraud_type", "High Velocity Anomaly")
            if typology == "legitimate":
                typology = "Statistical Anomaly"

            self.create_case(
                transaction_id=str(row["transaction_id"]),
                user_id=str(row["user_id"]),
                card_id=str(row["card_id"]),
                device_id=str(row["device_id"]),
                ip_address=str(row["ip_address"]),
                amount=float(row["amount"]),
                risk_score=float(row["composite_risk_score"]),
                risk_tier=str(row["risk_tier"]),
                fraud_typology=str(typology),
                rules_triggered=[],
                explanation_narrative=f"Transaction flagged with composite risk score of {row['composite_risk_score']:.1f}/100. Action recommended: {row['recommended_action']}.",
                assigned_investigator="Lead Analyst (AI Desk)",
                initial_notes=f"Auto-generated case for transaction {row['transaction_id']} at {row.get('merchant_category', 'Merchant')}.",
            )
            seeded += 1

        print(f"[CaseManager] Seeded {seeded} high-risk alert cases into SQLite DB ({self.db_path})")
        return seeded
